name: Deploy Bot

on:
  # Run on push to main branch
  push:
    branches: [ main ]
  # Run on pull requests to main branch
  pull_request:
    branches: [ main ]
  # Schedule to run every 5 hours
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest

    - name: Deploy to production
      run: |
        python -m pip install pm2
        pm2 start bot.py --name "kamasbot" --interpreter python3
        pm2 save
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
