name: Discord Bot Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 */5 * * *'  # Triggers every 5 hours and 30 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up Python path
      - name: Set up Python path
        run: |
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      # Step 5: Run the bot
      - name: Run the bot
        run: |
          python bot.py
